server {
  listen              80;
  server_name         paunin.local;

  access_log  /var/log/nginx/paunin.local.access.log;
  error_log   /var/log/nginx/paunin.local.error.log;

  client_max_body_size  50m;
  client_header_timeout 1200;
  client_body_timeout   1200;
  send_timeout          1200;
  keepalive_timeout     1200;

  sendfile off;


  root        /var/www/paunin.local/;
  index       index.php;

  location ~ \.php$ {
    fastcgi_pass    php:9000;
    fastcgi_index   index.php;
    include         fastcgi_params;

    fastcgi_connect_timeout 1200;
    fastcgi_send_timeout    1200;
    fastcgi_read_timeout    1200;

    fastcgi_param   PHP_VALUE       "date.timezone=Asia/Saigon\n max_execution_time=1200\n max_input_time=1200\n memory_limit=256M\n post_max_size=128M\n upload_max_filesize=64M\n";
    fastcgi_param   SCRIPT_FILENAME $document_root$fastcgi_script_name;
    fastcgi_param   APPLICATION_ENV dev;
    fastcgi_param   HTTPS           $thttps;
  }

  error_page  403 /403.html;
  error_page  404 /404.html;
  error_page  500 502 503 504 /50x.html;

}
