apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  namespace: paunin-com
  name: paunin-com-web
  labels:
    app: paunin-com
spec:
  serviceName: paunin-com
  replicas: 1
  template:
    metadata:
      labels:
        app: paunin-com
    spec:
      containers:
        - name: nginx
          image: 199372285325.dkr.ecr.eu-central-1.amazonaws.com/paunin-com:latest
          imagePullPolicy: Always
          env:
            - name: "CONFIG_VERSION"
              value: "1"
          ports:
            - containerPort: 80
          volumeMounts:
            - mountPath:  /var/www/application/media/originals
              name: media-volume
      volumes:
        - name: media-volume
          persistentVolumeClaim:
            claimName: paunin-com-media-claim
