apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: paunin-com-media-claim
  namespace: paunin-com
  labels:
    app: paunin-com-media
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi