kind: Service
apiVersion: v1
metadata:
  name: paunin-com
  namespace: paunin-com
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-internal: 0.0.0.0/0
spec:
  selector:
    app: paunin-com
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30061
  type: LoadBalancer