kind: Service
apiVersion: v1
metadata:
  name: paunin-com
  namespace: paunin-com
  annotations:
    service.beta.kubernetes.io/external-traffic: Global
spec:
  selector:
    app: paunin-com
  ports:
    - port: 80
  type: LoadBalancer